### ISSUE TITLE
node-red-contrib-sm-bas not ready for Python 3.12

### ISSUE THREAD

**Issue by thunermay** [SequentMicrosystems/megabas-rpi#18]
I tried installing the node-red-contrib-sm-bas package for my node-red environment.
I have Python version 3.12.0.

The problem is, distutils is not installed.

According to [https://stackoverflow.com/a/77233866/13097224](this) answer, distutils isn't anymore installed with Python 3.12

```
2024-06-27T19:01:08.334Z Install : node-red-contrib-sm-bas 1.0.1

2024-06-27T19:01:08.347Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-sm-bas@1.0.1
2024-06-27T19:01:08.538Z [err] npm
2024-06-27T19:01:08.538Z [err]  WARN config production Use `--omit=dev` instead.
2024-06-27T19:01:10.684Z [err] npm ERR! code
2024-06-27T19:01:10.684Z [err]  1
2024-06-27T19:01:10.684Z [err] npm 
2024-06-27T19:01:10.684Z [err] ERR!
2024-06-27T19:01:10.684Z [err]  path /Users/thunermay/.node-red/node_modules/i2c-bus
2024-06-27T19:01:10.685Z [err] npm ERR!
2024-06-27T19:01:10.685Z [err]  command failed
2024-06-27T19:01:10.685Z [err] npm ERR! command sh -c node-gyp rebuild
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info it worked if it ends with ok
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info using node-gyp@9.4.0
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info using node@20.9.0 | darwin | arm64
2024-06-27T19:01:10.685Z [err] npm ERR!
2024-06-27T19:01:10.685Z [err]  gyp info find Python using Python version 3.12.3 found at "/opt/homebrew/opt/python@3.12/bin/python3.12"
2024-06-27T19:01:10.685Z [err] npm ERR!
2024-06-27T19:01:10.685Z [err]  gyp info spawn /opt/homebrew/opt/python@3.12/bin/python3.12
2024-06-27T19:01:10.685Z [err] npm
2024-06-27T19:01:10.685Z [err]  ERR! gyp info spawn args [
2024-06-27T19:01:10.685Z [err] npm ERR!
2024-06-27T19:01:10.685Z [err]  gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   'binding.gyp',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '-f',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   'make',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '-I',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '/Users/thunermay/.node-red/node_modules/i2c-bus/build/config.gypi',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '-I',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '-I',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '/Users/thunermay/Library/Caches/node-gyp/20.9.0/include/node/common.gypi',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '-Dvisibility=default',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/thunermay/Library/Caches/node-gyp/20.9.0',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/thunermay/Library/Caches/node-gyp/20.9.0/<(target_arch)/node.lib',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/thunermay/.node-red/node_modules/i2c-bus',
2024-06-27T19:01:10.685Z [err] npm
2024-06-27T19:01:10.685Z [err]  ERR! gyp info spawn args   '-Dnode_engine=v8',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '--depth=.',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '--no-parallel',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '--generator-output',
2024-06-27T19:01:10.685Z [err] npm ERR!
2024-06-27T19:01:10.685Z [err]  gyp info spawn args   'build',
2024-06-27T19:01:10.685Z [err] npm ERR! gyp info spawn args   '-Goutput_dir=.'
2024-06-27T19:01:10.685Z [err] npm
2024-06-27T19:01:10.685Z [err]  ERR! gyp info spawn args ]
2024-06-27T19:01:10.685Z [err] npm 
2024-06-27T19:01:10.685Z [err] ERR!
2024-06-27T19:01:10.685Z [err]  Traceback (most recent call last):
2024-06-27T19:01:10.685Z [err] npm 
2024-06-27T19:01:10.685Z [err] ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
2024-06-27T19:01:10.685Z [err] npm ERR!
2024-06-27T19:01:10.685Z [err]      import gyp  # noqa: E402
2024-06-27T19:01:10.685Z [err] npm ERR!
2024-06-27T19:01:10.685Z [err]      ^^^^^^^^^^
2024-06-27T19:01:10.685Z [err] npm ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
2024-06-27T19:01:10.685Z [err] npm ERR!     import gyp.input
2024-06-27T19:01:10.685Z [err] npm
2024-06-27T19:01:10.685Z [err]  ERR!   File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
2024-06-27T19:01:10.685Z [err] npm ERR!     from distutils.version import StrictVersion
2024-06-27T19:01:10.685Z [err] npm ERR! ModuleNotFoundError: No module named 'distutils'
2024-06-27T19:01:10.685Z [err] npm ERR! gyp ERR! configure error 
2024-06-27T19:01:10.685Z [err] npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
2024-06-27T19:01:10.685Z [err] npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
2024-06-27T19:01:10.685Z [err] npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
2024-06-27T19:01:10.685Z [err] npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
2024-06-27T19:01:10.685Z [err] npm ERR! gyp ERR! System Darwin 23.5.0
2024-06-27T19:01:10.685Z [err] npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
2024-06-27T19:01:10.685Z [err] npm ERR! gyp ERR! cwd /Users/thunermay/.node-red/node_modules/i2c-bus
2024-06-27T19:01:10.685Z [err] npm ERR! gyp ERR! node -v v20.9.0
2024-06-27T19:01:10.685Z [err] npm ERR! gyp ERR! node-gyp -v v9.4.0
2024-06-27T19:01:10.685Z [err] npm ERR! gyp ERR! not ok
2024-06-27T19:01:10.686Z [err] 
2024-06-27T19:01:10.686Z [err] npm ERR! A complete log of this run can be found in: /Users/thunermay/.npm/_logs/2024-06-27T19_01_08_515Z-debug-0.log
2024-06-27T19:01:10.689Z rc=1
```

This is probably a simple but cruical fix.

**Comment by alexburcea2877** [comment]
No answer: assuming the problem was solved
